fix(action): remove set-action
DelineaXPM/dsv-github-action pull request #23
Opened 2022-10-14 08:16 UTC by mariiatuzovska

* remove ::set-output action
* make setting env by default

2022-10-14 09:07 UTC, andrii-zakurenyi commented on README.md
> +### Set Output to Job Scope Using Environment Variables
please remove this header

2022-10-14 09:28 UTC, mariiatuzovska commented
The integration test should fail because it uses default branch as a source

2022-10-14 13:51 UTC, sheldonhull requested changes
Did running the integration test locally succeed? (Prebuilt and directions in developer.md) 

assuming failure on on test here is because the structure out the outputs changed while the app didn’t get published yet. 

Also you’ll want to follow that release notes process to ensure it generates a new changelog via changie.  See changie cli tool directions. That is what triggers the release process

2022-10-17 12:39 UTC, mariiatuzovska commented
Integration tests ran successfully on local machine.

2022-10-17 14:01 UTC, sheldonhull requested changes
Minor changelog clarification and improved release notes please

2022-10-17 14:01 UTC, sheldonhull commented on .changes/unreleased/Removed-20221017-155023.yaml
> +body: ::set-output action
I see you updated the changelog file. Not sure if you did this manually. Changie batch and merge should get rid of the fragment files.

2022-10-17 15:33 UTC, sheldonhull requested changes
Highlight impact via breaking change note. Then we are good. 🎉

2022-10-17 15:33 UTC, sheldonhull commented on CHANGELOG.md
> +- Remove setEnv flag
```suggestion
- BREAKING CHANGE: Remove setEnv flag
```

2022-10-17 15:34 UTC, merged